=== fittner/SiMA/BW/src/xml/xmlSimpleXMLLoader/simpleloader_v1.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

<xsd:element name="BubbleWorld" >
 <xsd:complexType>
   <xsd:sequence>
   
     <xsd:element name="MobileItems">
       <xsd:complexType>
       <xsd:sequence>

          <xsd:element name="Bubble" id="ID" minOccurs="0" maxOccurs="unbounded">           
             <xsd:complexType>                                                 
              <xsd:all>                
                <xsd:element name="PosX" type="xsd:float"/>
                <xsd:element name="PosY" type="xsd:float"/>
                <xsd:element name="Direction" type="xsd:float"/>
              </xsd:all>               
              <xsd:attribute name="id" type="xsd:integer"/>              
             </xsd:complexType>                                 
          </xsd:element>

   
           <xsd:element name="Stone" minOccurs="0" maxOccurs="unbounded">
             <xsd:complexType>
             <xsd:all>
                <xsd:element name="PosX" type="xsd:float"/>
                <xsd:element name="PosY" type="xsd:float"/>
                <xsd:element name="Size" type="xsd:float"/>
             </xsd:all>
             </xsd:complexType>
           </xsd:element>


           <xsd:element name="Can" minOccurs="0" maxOccurs="unbounded">
              <xsd:complexType>
              <xsd:all>
                 <xsd:element name="PosX" type="xsd:float"/>
                 <xsd:element name="PosY" type="xsd:float"/>
              </xsd:all>
              </xsd:complexType>
           </xsd:element>



           <xsd:element name="RemoteBot" minOccurs="0" maxOccurs="1">
              <xsd:complexType>
              <xsd:all>
                 <xsd:element name="PosX" type="xsd:float"/>
                 <xsd:element name="PosY" type="xsd:float"/>
                 <xsd:element name="Direction" type="xsd:float"/>                 
              </xsd:all>
              </xsd:complexType>
           </xsd:element>


        </xsd:sequence>  
        </xsd:complexType>
     </xsd:element>  


     <xsd:element name="StationaryItems">
       <xsd:complexType>
       <xsd:sequence>

          <xsd:element name="Wall" minOccurs="0" maxOccurs="unbounded">
            <xsd:complexType>
            <xsd:all>
                <xsd:element name="PosX" type="xsd:float"/>
                <xsd:element name="PosY" type="xsd:float"/>
                <xsd:element name="Length" type="xsd:float"/>
                <xsd:element name="Width" type="xsd:float"/>
                <xsd:element name="Direction" type="xsd:float"/>
            </xsd:all>
            </xsd:complexType>
          </xsd:element>

        </xsd:sequence>  
        </xsd:complexType>
      </xsd:element>
   
  
    <xsd:element name="Window" minOccurs="1" maxOccurs="1">
      <xsd:complexType>
         <xsd:all>
            <xsd:element name="Width" type="xsd:float"/>
            <xsd:element name="Height" type="xsd:float"/>
         </xsd:all>
      </xsd:complexType>
    </xsd:element>

         
  </xsd:sequence> 
  </xsd:complexType>
</xsd:element>

</xsd:schema>

=== fittner/SiMA/BW/src/xml/xmlSimpleXMLLoader/config1.xml
<?xml version="1.0" ?> 
<BubbleWorld  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="file:/S:/ARS/PA/BWv1/BW/src/xml/xmlSimpleXMLLoader/simpleloader_v1.xsd">


<MobileItems>

  <Bubble id="4"> 
    <PosX>15</PosX>	
    <PosY>15</PosY>
    <Direction>0.0</Direction>
  </Bubble>
    
  <Bubble id="40"> 
    <PosX>15</PosX>	
    <PosY>50</PosY>
    <Direction>3.14</Direction>
  </Bubble>

  <Bubble id="56"> 
    <PosX>50</PosX>	
    <PosY>50</PosY>
    <Direction>2.7</Direction>
  </Bubble>

  <Bubble id="57">
    <PosX>50</PosX>	
    <PosY>15</PosY>
    <Direction>5.34</Direction>
  </Bubble>


  <Stone> 
    <PosX>30</PosX>	
    <PosY>30</PosY>
    <Size>5</Size>	
  </Stone>
    
  <Stone> 
    <PosX>150</PosX>	
    <PosY>40</PosY>
    <Size>40</Size>	
  </Stone>

  <Can>
  	<PosX>150</PosX>
  	<PosY>75</PosY>
  </Can>
  
  <Can>
  	<PosX>190</PosX>
  	<PosY>190</PosY>
  </Can>
  
  <Can>
  	<PosX>75</PosX>
  	<PosY>150</PosY>
  </Can>  
  
  <RemoteBot>
    <PosX>130</PosX>
    <PosY>180</PosY>
    <Direction>1.2</Direction>
  </RemoteBot>
  

  

</MobileItems>


<StationaryItems>

  <Wall> 
    <PosX>180</PosX>	
    <PosY>10</PosY>
    <Length>50.0</Length>
    <Width>3.0</Width>
    <Direction>4.71225</Direction>	
  </Wall>
 
</StationaryItems>

<Window>
   <Width>200</Width>
   <Height>200</Height>
</Window> 
   
   
</BubbleWorld>
